services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shade_calculator
      MYSQL_USER: shade_calculator
      MYSQL_PASSWORD: shade_calculator
    ports:
      - "3309:3306"
    networks:
      - shade-calculator-network

#  backend:
#    image: shade-calculator-backend
#    build:
#      context: .
#      dockerfile: Dockerfile
#    environment:
#      DB_URL: jdbc:mysql://mysql:3306/shade_calculator
#      DB_USERNAME: shade_calculator
#      DB_PASSWORD: shade_calculator
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mysql
#    networks:
#      - shade-calculator-network

networks:
    shade-calculator-network:
        driver: bridge